services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=pixelflow
      - RABBITMQ_DEFAULT_PASS=pixelflow
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data: